Vagrant.configure(2) do |config|

  config.vm.box = "chef/debian-7.4"
  #config.vm.network "private_network", ip: "192.168.33.20"
  config.vm.network "public_network"

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.name = "jukebox"
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "provision.sh"

end
